DROP TABLE REGIST;

CREATE TABLE REGIST (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    ADDRESS VARCHAR2(40),
    GRADE VARCHAR2(20),
    PHONE VARCHAR2(20)
);

DROP SEQUENCE RG_SEQ;

CREATE SEQUENCE RG_SEQ
        INCREMENT BY 1
       START WITH 101
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

INSERT INTO REGIST VALUES(RG_SEQ.NEXTVAL,'±èÁö¿ì','¼­¿ï½Ã','SILVER','010-1111-1111');
INSERT INTO REGIST VALUES(RG_SEQ.NEXTVAL,'È«±æµ¿','ÀÎÃµ½Ã','GOLD','010-2222-2222');
INSERT INTO REGIST VALUES(RG_SEQ.NEXTVAL,'À²°î','±èÆ÷½Ã','VIP','010-3333-3333');

SELECT * FROM REGIST;

COMMIT;